### ISSUE TITLE
SQL-lite / MySQL comparision

### ISSUE THREAD

**Issue by tkrabel** [tkrabel/django#1]
- [ ]  Difference between SQL-lite and MYSQL

- [ ] What solution to use

**Comment by tkrabel** [comment]
Idea: use RasPi as server for DB and Website. Linux --> Multi-threaded

**Comment by DatenBergwerker** [comment]
SQL Lite is a lightweight database implementation running with SQL-command language. It does not additional server soft/hardware to run which is the major difference between SQLLite and traditional SQL-approaches. SQLLite is usually added to the application via a library reference. In Python3.x SQLLlite3 is part of the standard library and does not require any additional installs. SQLLite databases generally do not exceed the size of a few hundred kilobytes and all tables, data, references, etc. is saved to a single file. It does not offer any kind of privilege administration and the current user privileges are derived directly from the filesystem. Concurrent writing operations to the databases are also not possible and will be processed serially.

https://www.sqlite.org/about.html
